INSERT OR REPLACE INTO placement_questions (
  question_id,
  section,
  question_type,
  passage,
  question_text,
  option_a,
  option_b,
  option_c,
  option_d,
  correct_option,
  explanation,
  order_index,
  is_active
) VALUES
  (
    'P001',
    'Grammar',
    'multiple_choice',
    NULL,
    'Which sentence is grammatically correct?',
    'She don''t enjoy studying in the morning.',
    'She doesn''t enjoy studying in the morning.',
    'She doesn''t enjoys studying in the morning.',
    'She not enjoy studying in the morning.',
    'B',
    'Use "does not" + base verb: "doesn''t enjoy" is correct.',
    1,
    1
  ),
  (
    'P002',
    'Vocabulary',
    'multiple_choice',
    NULL,
    'Choose the best word to complete the sentence: "The new policy will ____ collaboration between departments."',
    'hinder',
    'facilitate',
    'diminish',
    'prevent',
    'B',
    '"Facilitate" means to make something easier, which matches the context.',
    2,
    1
  ),
  (
    'P003',
    'Reading',
    'inference',
    'Many city councils are expanding bike lanes because short car trips produce disproportionate congestion and emissions.',
    'What is the main reason city councils are expanding bike lanes?',
    'To reduce long-distance travel demand.',
    'To make cycling mandatory in urban areas.',
    'To address pollution and traffic caused by short car trips.',
    'To support professional cycling events.',
    'C',
    'The passage explicitly links short car trips to congestion and emissions, and bike lanes as a response.',
    3,
    1
  ),
  (
    'P004',
    'Listening',
    'detail',
    'In a university orientation talk, students are advised to attend workshops early because slots fill quickly before midterm season.',
    'Why are students advised to attend workshops early?',
    'Workshops are only available to first-year students.',
    'Workshop places become limited later in the term.',
    'Workshops are free only in the first week.',
    'Workshop topics are repeated after midterms.',
    'B',
    'The talk says slots fill quickly, so students should attend before demand peaks.',
    4,
    1
  ),
  (
    'P005',
    'Grammar',
    'multiple_choice',
    NULL,
    'Complete the conditional sentence: "If I ____ more time, I would join the speaking club."',
    'have',
    'had',
    'will have',
    'am having',
    'B',
    'This is a second conditional structure: If + past simple, would + base verb.',
    5,
    1
  ),
  (
    'P006',
    'Reading',
    'main_idea',
    'Remote teams that set clear communication windows report fewer misunderstandings and faster project turnaround.',
    'What is the best summary of the statement?',
    'Remote teams should avoid synchronous meetings entirely.',
    'Clear communication schedules improve remote team performance.',
    'Project speed depends mostly on individual talent.',
    'Misunderstandings are unavoidable in remote work.',
    'B',
    'The statement emphasizes clearer communication windows leading to better outcomes.',
    6,
    1
  ),
  (
    'P007',
    'Vocabulary',
    'collocation',
    NULL,
    'Which option has the most natural academic collocation?',
    'make a research',
    'do a research',
    'conduct research',
    'perform a research',
    'C',
    'In academic English, the standard collocation is "conduct research".',
    7,
    1
  ),
  (
    'P008',
    'Reading',
    'inference',
    'Despite the rapid expansion of urban centres across Southeast Asia, many rural communities have retained strong cultural identities, partly because infrastructure investment has lagged significantly behind economic growth.',
    'What does the author imply about rural communities in Southeast Asia?',
    'They have been negatively affected by urbanisation.',
    'Economic growth has uniformly benefited all regions.',
    'Limited infrastructure helped preserve cultural identity.',
    'Urban and rural communities share similar identities.',
    'C',
    'The sentence suggests slower infrastructure development helped preserve local cultural patterns.',
    8,
    1
  ),
  (
    'P009',
    'Writing',
    'coherence',
    NULL,
    'Which sentence is the best concluding sentence for an opinion essay?',
    'That is all I want to say about this topic.',
    'In conclusion, stricter public transport policies are essential to reduce congestion and improve air quality.',
    'People can think whatever they want, and there are many ideas.',
    'Transport is a thing and cities are also things.',
    'B',
    'A strong conclusion restates the main position clearly and formally.',
    9,
    1
  ),
  (
    'P010',
    'Vocabulary',
    'paraphrase',
    NULL,
    'Choose the best paraphrase of "significant" in this sentence: "There has been a significant increase in online learning."',
    'minor',
    'substantial',
    'temporary',
    'uncertain',
    'B',
    '"Substantial" is the closest synonym to "significant" in this context.',
    10,
    1
  );
