INSERT OR REPLACE INTO placement_questions (
  question_id,
  section,
  question_type,
  passage,
  question_text,
  option_a,
  option_b,
  option_c,
  option_d,
  correct_option,
  explanation,
  order_index,
  is_active
) VALUES
  (
    'P011',
    'Grammar',
    'multiple_choice',
    NULL,
    'Choose the correct sentence.',
    'The number of applicants are increasing each year.',
    'The number of applicants is increasing each year.',
    'The number of applicants were increasing each year.',
    'The number of applicants increase each year.',
    'B',
    'The subject is "number" (singular), so the verb should be "is".',
    11,
    1
  ),
  (
    'P012',
    'Vocabulary',
    'paraphrase',
    NULL,
    'Select the closest meaning of "crucial" in academic writing.',
    'optional',
    'trivial',
    'essential',
    'delayed',
    'C',
    '"Crucial" means very important, closest to "essential".',
    12,
    1
  ),
  (
    'P013',
    'Reading',
    'inference',
    'Several schools that delayed smartphone use until break time reported higher classroom focus and fewer interruptions.',
    'What can be inferred from the statement?',
    'Smartphones should be banned permanently from schools.',
    'Controlled phone use may improve attention during lessons.',
    'Students learn best when using phones continuously.',
    'Classroom interruptions are unrelated to phone use.',
    'B',
    'The statement links delayed phone use with better focus and fewer interruptions.',
    13,
    1
  ),
  (
    'P014',
    'Listening',
    'detail',
    'In a campus announcement, students are reminded that library study rooms must be booked at least one day in advance during exam week.',
    'According to the announcement, what must students do during exam week?',
    'Book study rooms on the same day.',
    'Reserve study rooms one day earlier.',
    'Use only open reading areas.',
    'Get approval from their lecturer first.',
    'B',
    'The announcement clearly says bookings should be made at least one day in advance.',
    14,
    1
  ),
  (
    'P015',
    'Grammar',
    'multiple_choice',
    NULL,
    'Complete the sentence correctly: "The report, along with its appendices, ____ submitted yesterday."',
    'were',
    'have been',
    'was',
    'are',
    'C',
    'The main subject is "report" (singular), so "was" is correct.',
    15,
    1
  ),
  (
    'P016',
    'Vocabulary',
    'collocation',
    NULL,
    'Choose the best collocation for formal writing.',
    'heavy rain caused serious traffic',
    'strong rain caused serious traffic',
    'thick rain caused serious traffic',
    'dense rain caused serious traffic',
    'A',
    '"Heavy rain" is the natural collocation in English.',
    16,
    1
  ),
  (
    'P017',
    'Reading',
    'main_idea',
    'Companies that provide structured onboarding often retain employees longer and reduce early-stage errors.',
    'What is the main idea?',
    'Onboarding is expensive and should be limited.',
    'Employee retention is mostly unrelated to training.',
    'Structured onboarding improves retention and accuracy.',
    'Early-stage errors cannot be reduced.',
    'C',
    'The sentence directly links structured onboarding to better retention and fewer errors.',
    17,
    1
  ),
  (
    'P018',
    'Writing',
    'coherence',
    NULL,
    'Which transition best introduces a contrasting point in an essay?',
    'For example,',
    'In contrast,',
    'As a result,',
    'Similarly,',
    'B',
    '"In contrast," is used to introduce an opposing or different idea.',
    18,
    1
  ),
  (
    'P019',
    'Grammar',
    'multiple_choice',
    NULL,
    'Choose the correct verb form: "By the time we arrived, the lecture _____."',
    'starts',
    'had started',
    'has started',
    'was starting',
    'B',
    'Past perfect is used for an action completed before another past action.',
    19,
    1
  ),
  (
    'P020',
    'Vocabulary',
    'paraphrase',
    NULL,
    'Pick the best paraphrase of "decline" in this context: "There was a decline in attendance."',
    'increase',
    'drop',
    'delay',
    'improvement',
    'B',
    '"Decline" in this context means a reduction or drop.',
    20,
    1
  ),
  (
    'P021',
    'Reading',
    'detail',
    'A travel notice states that passengers must arrive at least 45 minutes before domestic departures to complete security checks.',
    'According to the notice, when should domestic passengers arrive?',
    'At least 15 minutes before departure.',
    'Exactly 30 minutes before departure.',
    'At least 45 minutes before departure.',
    'Only when boarding begins.',
    'C',
    'The notice explicitly gives a minimum of 45 minutes before departure.',
    21,
    1
  ),
  (
    'P022',
    'Listening',
    'inference',
    'During a workshop, the speaker says attendance dropped after sessions were moved to late Friday afternoons.',
    'What does the speaker most likely suggest?',
    'The workshop content is too advanced.',
    'The schedule may be affecting attendance.',
    'Students prefer online workshops only.',
    'Friday sessions are always full.',
    'B',
    'The timing change is presented as a likely reason for lower attendance.',
    22,
    1
  ),
  (
    'P023',
    'Grammar',
    'multiple_choice',
    NULL,
    'Choose the correct article usage.',
    'She gave me an useful suggestion.',
    'She gave me useful suggestion.',
    'She gave me a useful suggestion.',
    'She gave me the useful suggestion generally.',
    'C',
    '"Useful" starts with a consonant sound (yoo), so use "a".',
    23,
    1
  ),
  (
    'P024',
    'Vocabulary',
    'word_form',
    NULL,
    'Select the correct word form: "The committee reached a _____ after two hours of discussion."',
    'decide',
    'decision',
    'decisive',
    'deciding',
    'B',
    'A noun is needed after the article "a": "decision".',
    24,
    1
  ),
  (
    'P025',
    'Reading',
    'inference',
    'Although online courses offer flexibility, completion rates are often higher when learners receive weekly feedback from instructors.',
    'What is implied about online learning?',
    'Flexibility alone guarantees completion.',
    'Instructor feedback can improve course completion.',
    'Weekly feedback is unnecessary in online courses.',
    'Online learning always has low completion rates.',
    'B',
    'The statement suggests feedback is an important factor in improving completion rates.',
    25,
    1
  ),
  (
    'P026',
    'Writing',
    'task_response',
    NULL,
    'Which thesis statement is the most direct for an IELTS opinion essay?',
    'There are many things to discuss about this issue.',
    'This essay will explore different views and some examples.',
    'I strongly believe governments should invest more in public transport to reduce congestion and pollution.',
    'Public transport has existed for a long time in many countries.',
    'C',
    'A strong thesis clearly states a position and main rationale.',
    26,
    1
  ),
  (
    'P027',
    'Grammar',
    'multiple_choice',
    NULL,
    'Complete the sentence: "If the team had prepared earlier, they _____ the deadline."',
    'will meet',
    'would have met',
    'would meet',
    'met',
    'B',
    'This is a third conditional: If + past perfect, would have + past participle.',
    27,
    1
  ),
  (
    'P028',
    'Vocabulary',
    'collocation',
    NULL,
    'Choose the most natural collocation.',
    'take a decision',
    'do a decision',
    'make a decision',
    'build a decision',
    'C',
    'The standard collocation is "make a decision".',
    28,
    1
  ),
  (
    'P029',
    'Reading',
    'inference',
    'A report notes that neighborhoods with more public parks recorded lower summer surface temperatures than nearby dense commercial areas.',
    'What conclusion is most supported?',
    'Commercial areas should close during summer.',
    'Public parks may help reduce urban heat effects.',
    'Surface temperature is unrelated to land use.',
    'Dense areas always contain more trees.',
    'B',
    'The comparison indicates parks are associated with lower surface temperatures.',
    29,
    1
  ),
  (
    'P030',
    'Writing',
    'tone',
    NULL,
    'Which sentence has the most appropriate formal tone for IELTS Writing Task 2?',
    'Kids these days are kinda addicted to phones.',
    'Young people are, like, always on social media.',
    'Many adolescents are excessively dependent on smartphones for daily communication.',
    'Phones are bad and that is basically it.',
    'C',
    'Option C uses precise and formal academic wording.',
    30,
    1
  );
